version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: generic-postgres-db
    restart: unless-stopped
    environment:
 GRES_DB: ${POSTGRES_DB:-generic_db}
    ports:
      -

